backend:
  name: github # Mude o backend para github
  repo: morrigangray/informes-brasil-site # Substitua pelo SEU_USUARIO/NOME_DO_REPO
  branch: main # Ou a branch que você usa como principal (ex: main ou master)

# Onde os media (imagens, etc.) serão guardados no seu repositório
media_folder: "public/images/uploads"
# Como o site irá aceder a essas imagens
public_folder: "/images/uploads"

collections:
  - name: "noticias" # O nome da nossa coleção de conteúdo
    label: "Notícias" # Como aparecerá no painel
    folder: "content/noticias" # A pasta onde os ficheiros das notícias serão guardados
    create: true # Permitir a criação de novas notícias
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Como o nome do ficheiro será gerado
    fields: # Os campos do nosso formulário de notícias
      - { label: "Título", name: "Title", widget: "string" }
      - { label: "Data de Publicação", name: "Date", widget: "datetime" }
      - { label: "Categoria", name: "Category", widget: "string", required: false }
      - { label: "Imagem de Destaque", name: "Image", widget: "image" }
      - { label: "Corpo da Notícia", name: "body", widget: "markdown" }