backend:
  name: github
  repo: morrigangray/informes-brasil-site
  branch: main
  base_url: https://decap-cms-oauth.glitch.me

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "noticias"
    label: "Notícias"
    folder: "content/noticias"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título", name: "Title", widget: "string" }
      - { label: "Data de Publicação", name: "Date", widget: "datetime" }
      - { label: "Categoria", name: "Category", widget: "string", required: false }
      - { label: "Imagem de Destaque", name: "Image", widget: "image" }
      - { label: "Corpo da Notícia", name: "body", widget: "markdown" }