backend:
  name: firebase
  config:
    apiKey: "AIzaSyCDUy9NyrdcxGff6L5He0lsFJSDJwyxM3w"
    authDomain: "informes-brasil-news.firebaseapp.com"
    use_json_parser: true

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "noticias"
    label: "Notícias"
    folder: "_noticias" # Este campo não é usado pelo backend do Firebase, mas é mantido por compatibilidade
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "Title", widget: "string" }
      - { label: "Data de Publicação", name: "Date", widget: "datetime" }
      - { label: "Categoria", name: "Category", widget: "string", required: false }
      - { label: "Imagem de Destaque", name: "Image", widget: "image" }
      - { label: "Corpo da Notícia", name: "body", widget: "markdown" }

media_folder: "public/images/uploads" # Onde as imagens das notícias serão guardadas
public_folder: "/images/uploads" # Como o site irá aceder a essas imagens

collections:
  - name: "noticias" # O nome da nossa coleção de conteúdo
    label: "Notícias" # Como aparecerá no painel
    folder: "_noticias" # A pasta onde os ficheiros serão guardados
    create: true # Permitir a criação de novas notícias
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Como o nome do ficheiro será gerado
    fields: # Os campos do nosso formulário de notícias
      - { label: "Título", name: "Title", widget: "string" }
      - { label: "Data de Publicação", name: "Date", widget: "datetime" }
      - { label: "Categoria", name: "Category", widget: "string", required: false }
      - { label: "Imagem de Destaque", name: "Image", widget: "image" }
      - { label: "Corpo da Notícia", name: "body", widget: "markdown" }
